/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * card.java
 *
 * Created on 2 Aug, 2017, 4:32:30 PM
 */

package frames;

import javax.swing.JOptionPane;

/**
 *
 * @author mridulamadhur
 */
public class card extends javax.swing.JFrame {

    /** Creates new form card */
    public card() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        n4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        n6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        n7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel1.setText("Card Number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 30));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel2.setText("Expiry date :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 100, 20));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel3.setText("CVV :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 36));
        jLabel5.setText("PAYMENT THROUGH CARD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel6.setText("MM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel7.setText("YYYY");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 150, -1));
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, -1));
        getContentPane().add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 30, -1));
        getContentPane().add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 70, -1));

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24));
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 140, 40));
        getContentPane().add(n6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 100, -1));

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel8.setText("Enter mobile no. :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18));
        jButton3.setText("GO BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, 40));
        getContentPane().add(n7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));

        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel9.setText("Name on card :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 140, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(((n1.getText()).equals("")==true)||((n2.getText()).equals("")==true)||((n3.getText()).equals("")==true)||((n4.getText()).equals("")==true)||((n6.getText()).equals("")==true)||((n7.getText()).equals("")==true))
{JOptionPane.showMessageDialog(null,"PLEASE COMPLETE ALL  FIELDs.");}String a=n2.getText();

if (a.length()==16){CASH b=new CASH();
b.setVisible(true);
dispose();JOptionPane.showMessageDialog(null,"Transaciton authourized");

}
else
    JOptionPane.showMessageDialog(null, "Please enter a valid 16 digit card no.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  payment n=new payment();     // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField n6;
    private javax.swing.JTextField n7;
    // End of variables declaration//GEN-END:variables

}
