/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CASH.java
 *
 * Created on 28 Jul, 2017, 11:47:44 AM
 */

package frames;

import frames.payment;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mridulamadhur
 */
public class CASH extends javax.swing.JFrame {

    /** Creates new form CASH */
    public CASH() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        a = new javax.swing.JTable();
        n2 = new javax.swing.JTextField();
        c1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        N1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAYMENT THROUGH CASH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Baskerville Old Face", 0, 12))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 48));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel1.setText("ENTER USERNAME :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
        jPanel1.add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 160, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18));
        jLabel2.setText("ENTER ADDRESS :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18));
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, -1, 40));

        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18));
        jButton2.setText("GO BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, 40));

        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18));
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 40));

        a.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fandom ", "Item No.", "Item Name", "Quantity", "Size", "Rate", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(a);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 460, 190));
        jPanel1.add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 160, -1));

        c1.setFont(new java.awt.Font("Baskerville Old Face", 0, 24));
        c1.setText("Send to the saved address");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel1.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 320, 40));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 24));
        jLabel4.setText("TOTAL PRICE :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 30));

        N1.setEditable(false);
        jPanel1.add(N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 490, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
payment n=new payment();
n.setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
finale n=new finale();
n.setVisible(true);
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
if (c1.isSelected()==true)
{
String al=n1.getText(); String add;
  n2.setEditable(false);
try
      {Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");

       Statement stmt=con.createStatement();
       String query="select address from customer where username=\""+al+"\";";

       ResultSet rs=stmt.executeQuery(query);
       add = null;
       while(rs.next())
           add=rs.getString(1);
       n2.setText(add);
}
catch(Exception e)
{}
} 
else {n2.setText("");
n2.setEditable(true);
}
}//GEN-LAST:event_c1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 n1.setText("");
 n2.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
int sum=0; DefaultTableModel model=(DefaultTableModel)a.getModel();
int hey=a.getRowCount();
if (hey==0){
try{

Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","diti");

Statement stmt=con.createStatement();
String query="select * from cart;";
ResultSet rs=stmt.executeQuery(query);

while(rs.next())
{
String fandom=rs.getString("fandom");
String itemno=rs.getString("item_no");
String item=rs.getString("item");
int qty=rs.getInt("quantity");
int rate=rs.getInt("rate");
int total=rs.getInt("total");
sum=sum+total;
String size=rs.getString("size");

model.addRow(new Object[]{fandom,itemno,item,size,qty,rate,total});
        a.setRowHeight(35);
}}
catch(Exception e)
{;}}
N1.setText(""+sum);


// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CASH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N1;
    private javax.swing.JTable a;
    private javax.swing.JCheckBox c1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    // End of variables declaration//GEN-END:variables

}
