/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * finale.java
 *
 * Created on 17 Aug, 2017, 11:50:17 AM
 */

package frames;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MockingJay
 */
public class finale extends javax.swing.JFrame {

    /** Creates new form finale */
    public finale() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        a = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        N1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fandom", "Item no.", "Item", "Size", "Qty", "Rate", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        a.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                aPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(a);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 720, 270));

        jButton1.setText("GO BACK TO SHOPPING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 720, -1));

        jButton2.setText("PLACE ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 720, -1));

        jLabel1.setText("TOTAL:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                N1ActionPerformed(evt);
            }
        });
        getContentPane().add(N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_aPropertyChange
        // TODO add your handling code here:
}//GEN-LAST:event_aPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 int sum=0; DefaultTableModel model=(DefaultTableModel)a.getModel();
int hey=a.getRowCount();
if (hey==0){
try{

Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","diti");

Statement stmt=con.createStatement();
String query="select * from cart;";
ResultSet rs=stmt.executeQuery(query);

while(rs.next())
{
String fandom=rs.getString("fandom");
String itemno=rs.getString("item_no");
String item=rs.getString("item");
int qty=rs.getInt("quantity");
int rate=rs.getInt("rate");
int total=rs.getInt("total");
sum=sum+total;
String size=rs.getString("size");

model.addRow(new Object[]{fandom,itemno,item,size,qty,rate,total});
        a.setRowHeight(35);
}}
catch(Exception e)
{;}}
N1.setText(""+sum);
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try
{Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","diti");

Statement stmt=con.createStatement();
String query="delete from cart;";
stmt.executeUpdate(query);

}
catch(Exception e){}species n=new species();
n.setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JOptionPane.showMessageDialog(null, "Your order has been successfully placed. Thank You for Shopping With us.");
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_N1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_N1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N1;
    private javax.swing.JTable a;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
