/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * iceage.java
 *
 * Created on 17 Apr, 2017, 6:45:24 PM
 */

package frames;

import frames.species;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author MockingJay
 */
public class iceage extends javax.swing.JFrame {

    /** Creates new form iceage */
    public iceage() {
        initComponents();
    }

         public void method1(String fandom,String h,int q,String g,String size,int price,int tot)
    { int f=0;
      try{
   Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");
Statement stmt=conn.createStatement();
 String qwe="select item,size from cart ;";
 ResultSet rs=stmt.executeQuery(qwe);
 while(rs.next()){
 String hey=rs.getString("item");
 String siz=rs.getString("size");
if((g.equals(hey))&&(size.equals(siz)))
f++;}}
 catch(Exception e)
 {}
      if(f!=0)
          {try
 {
Connection cw=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");
Statement set=cw.createStatement();
        String qw="update cart set quantity=quantity+"+q+" where item_no=\""+h+"\";";
        String qwer="update cart set total=rate*quantity;";
        set.executeUpdate(qw);
        set.executeUpdate(qwer);
 JOptionPane.showMessageDialog(null,"Quantity sucessfully changed");
 }
catch(Exception e){JOptionPane.showMessageDialog(null, "Technical Errors");}
}
else{
     try
 {
 Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");
Statement stm=con.createStatement();
 String qwe="select * from products where product_code=\""+h+"\";";
 ResultSet rd=stm.executeQuery(qwe);
 while(rd.next()){
 fandom=rd.getString("fandoms");
price=rd.getInt("price");
 h=rd.getString("product_Code");
 tot=price*q;}
 }
catch(Exception e){JOptionPane.showMessageDialog(null,"error in connectivity");}
try{
    Connection cone=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");
  Statement stamt=cone.createStatement();
String qwer="insert into cart values(\""+fandom+"\",\""+h+"\",\""+g+"\","+q+",\""+size+"\","+price+","+tot+");";
stamt.executeUpdate(qwer);
}
catch(Exception e)
{JOptionPane.showMessageDialog(null,"Error in connectivity");}}}



 
public static boolean isDigit(String str)
{
  try
  {
    int a=Integer.parseInt(str);
    return true;
  }
  catch(NumberFormatException nfe)
  {
    return false;
  }
 
}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        c2 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        c3 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        c4 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        c5 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        q5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/i1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 180));

        c1.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18)); // NOI18N
        c1.setText("SCRAT TSHIRT");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, 40));

        jLabel6.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        jLabel6.setText("QTY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        jLabel7.setText("SIZE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/i2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 170, 180));

        c2.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        c2.setText("ICE AGE BLUE TSHIRT");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 220, 40));

        jLabel8.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        jLabel8.setText("SIZE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        jLabel9.setText("QTY");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/i3.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 130, 180));

        c3.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        c3.setText("SID TSHIRT");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 170, 40));

        jLabel10.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        jLabel10.setText("SIZE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        jLabel11.setText("QTY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, -1, -1));

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        getContentPane().add(cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/i4.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 170, 180));

        c4.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        c4.setText("MANNY MUG");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 170, 40));

        jLabel13.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        jLabel13.setText("QTY");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/15.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 170, 180));

        c5.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        c5.setText("THE WHACK PACK MUG");
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 240, 40));

        jLabel15.setFont(new java.awt.Font("Ice Age Movie Font", 0, 18));
        jLabel15.setText("QTY");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, -1, -1));

        jButton1.setFont(new java.awt.Font("Ice Age Movie Font", 0, 24));
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, -1, -1));

        jButton2.setFont(new java.awt.Font("Ice Age Movie Font", 0, 24));
        jButton2.setText("ADD TO CART");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, -1, -1));
        getContentPane().add(q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 30, -1));
        getContentPane().add(q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 40, -1));
        getContentPane().add(q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 40, -1));
        getContentPane().add(q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 50, -1));
        getContentPane().add(q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 40, -1));

        jLabel12.setText("Price:449");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 60, -1));

        jLabel14.setText("Price:199");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 60, -1));

        jLabel16.setText("Price:199");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 60, -1));

        jLabel17.setText("Price:299");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 60, -1));

        jLabel18.setText("Price:299");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c1ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c2ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c3ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c4ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_c5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           movies n= new movies();
        n.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if ((c1.isSelected()==false)&&(c2.isSelected()==false)&&(c3.isSelected()==false)&&(c4.isSelected()==false)&&(c5.isSelected()==false))
  { JOptionPane.showMessageDialog(null,"PLEASE SELECT ALTEAST 1 ITEM...");}


         if(c1.isSelected()==true)
{String z=q1.getText();
 if(isDigit(z)==false)
 {JOptionPane.showMessageDialog(null, "Please enter the Valid Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size=(String) cb1.getSelectedItem()  ;
   String itnam=c1.getText();
   int tot=0,price=0;
   String fandom = null,procod = "IA1011";
  method1(fandom,procod,a,itnam,size,price,tot);}}




if(c2.isSelected()==true)
{String z=q2.getText();
if(isDigit(z)==false)
 {JOptionPane.showMessageDialog(null, "Please enter the Valid Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size=(String) cb2.getSelectedItem()  ;
   String itnam=c2.getText();
   int tot=0,price=0;
   String fandom = null,procod = "IA1012";
  method1(fandom,procod,a,itnam,size,price,tot);}}
         


if(c3.isSelected()==true)
{String z=q3.getText();
 if(isDigit(z)==false)
 {JOptionPane.showMessageDialog(null, "Please enter the Valid Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size=(String) cb3.getSelectedItem()  ;
   String itnam=c3.getText();
   int tot=0,price=0;
   String fandom = null,procod = "IA1013";
  method1(fandom,procod,a,itnam,size,price,tot);}}




   if(c4.isSelected()==true)
{String z=q4.getText();
if(isDigit(z)==false)
 {JOptionPane.showMessageDialog(null, "Please enter the Valid Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size="null"  ;
   String itnam=c4.getText();
   int tot=0,price=0;
   String fandom = null,procod = "IA1021";
  method1(fandom,procod,a,itnam,size,price,tot);}}



   if(c5.isSelected()==true)
{String z=q5.getText();
if(isDigit(z)==false)
 {JOptionPane.showMessageDialog(null, "Please enter the Valid Quantity.");
 }
 else{
 int a=Integer.parseInt(z);
  String size="null";
   String itnam=c5.getText();
   int tot=0,price=0;
   String fandom = null,procod = "IA1022";
  method1(fandom,procod,a,itnam,size,price,tot);}}


NewJFrame n=new NewJFrame();
n.setVisible(true);


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iceage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q5;
    // End of variables declaration//GEN-END:variables

}
