/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 14 Apr, 2017, 1:28:16 PM
 */

package frames;

import frames.RegisterForm;
import frames.one;
import frames.species;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MockingJay
 */
public class Login extends javax.swing.JFrame {

    /** Creates new form Login */
    public Login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pwds = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("AR ESSENCE", 1, 24));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ENTER USERNAME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 290, 30));

        jLabel4.setFont(new java.awt.Font("AR ESSENCE", 1, 24));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENTER PASSWORD:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        cb.setBackground(new java.awt.Color(0, 0, 0));
        cb.setFont(new java.awt.Font("Tahoma", 0, 14));
        cb.setForeground(new java.awt.Color(255, 255, 255));
        cb.setText("SHOW PASSWORD");
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        jPanel1.add(cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/Fandom shop.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FORGOT PASSWORD?");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, -1, 20));

        jButton1.setFont(new java.awt.Font("Constantia", 1, 24));
        jButton1.setText("GO!!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 290, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/back_1.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html>NOT A USER YET.. <b>REGISTER HERE...");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 290, -1));
        jPanel1.add(pwds, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 290, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    pwds.setVisible(true);
    pass.setVisible(false);
    try{
   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");
    Statement stmt=con.createStatement();

    String query="drop table cart;";
    stmt.executeUpdate(query);
   }
    catch(Exception e)
    {}
    try
    { Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");
     Statement hello=con.createStatement();
    String qwerty="create table cart(fandom char(30),item_no varchar(50),item varchar(100),quantity int,size char(10) default \"N.A.\",rate int,total int);";
    hello.executeUpdate(qwerty);}
    catch(Exception e)
    {}
    }//GEN-LAST:event_formWindowActivated

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
       if(pwds.isVisible()==true)
       {String a=new String(pwds.getPassword());
                pass.setVisible(true);
        pwds.setVisible(false);
        pass.setText(a);
       }
       else
       {String a=pass.getText();
       pwds.setText(a);
       pass.setVisible(false);
       pwds.setVisible(true);}
       // TODO add your handling code here:
}//GEN-LAST:event_cbActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       RegisterForm s=new RegisterForm();
       s.setVisible(true);
       dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
      one s= new one();
      s.setVisible(true);
      dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String a=username.getText();
     String b="";
     if(cb.isSelected()==true)
     {b=pass.getText();}
     else
     {b=new String(pwds.getPassword());}
     b=b.toLowerCase();
      
     
     if((b.equals(""))||(a.equals("")))
         JOptionPane.showMessageDialog(null,"PLEASE ENTER BOTH USERNAME AND PASSWORD");
     else
     {try
      {Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");
      
       Statement stmt=con.createStatement();
       String query="select password from customer where username=\""+a+"\";";
 
       ResultSet rs=stmt.executeQuery(query);
       String pd = null;
       while(rs.next())
           pd=rs.getString(1);
       
     
       { if(b.equals(pd)){
       species n=new species();
       n.setVisible(true);
     
       dispose();}
       else JOptionPane.showMessageDialog(null,"username and password do not match..");
   }
      }
      catch(Exception e)
      {JOptionPane.showMessageDialog(null,"username and password do not exist");}}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
JOptionPane.showMessageDialog(null,"PLEASE ASK MS. AKSHAYA GANGURDE (OWNER)");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pass;
    private javax.swing.JPasswordField pwds;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}
