/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MickeyMousedisney.java
 *
 * Created on 19 Apr, 2017, 11:06:58 AM
 */

package frames;

import javax.swing.JOptionPane;

/**
 *
 * @author mridulamadhur
 */
public class mm extends javax.swing.JFrame {

    /** Creates new form MickeyMousedisney */
    public mm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        n3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        n4 = new javax.swing.JTextField();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c1 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        n2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        c4 = new javax.swing.JCheckBox();
        n5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandoms/mm1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(n3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 30, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandoms/mm2.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Wicked Mouse", 0, 11));
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Wicked Mouse", 0, 11));
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 30, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandoms/mm3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 180));
        getContentPane().add(n4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 30, -1));

        c2.setFont(new java.awt.Font("Wicked Mouse", 0, 14));
        c2.setText("mickey mouse soft-toy");
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        c3.setFont(new java.awt.Font("Wicked Mouse", 0, 14));
        c3.setText("mickey mouse soft-toy");
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Wicked Mouse", 0, 11));
        jLabel7.setText("Quantity");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandoms/mm4.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        c1.setFont(new java.awt.Font("Wicked Mouse", 0, 14));
        c1.setText("mickey mouse bedsheet");
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        c5.setFont(new java.awt.Font("Wicked Mouse", 0, 14));
        c5.setText("mickey mouse t-shirt");
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        jLabel8.setFont(new java.awt.Font("Wicked Mouse", 0, 11));
        jLabel8.setText("Quantity");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 30, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandoms/mm5.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, 200));

        c4.setFont(new java.awt.Font("Wicked Mouse", 0, 14));
        c4.setText("mickey mouse pendent");
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));
        getContentPane().add(n5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 30, -1));

        jLabel10.setFont(new java.awt.Font("Wicked Mouse", 0, 11));
        jLabel10.setText("Quantity");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        jButton1.setFont(new java.awt.Font("Wicked Mouse", 0, 24));
        jButton1.setText("ADD TO CART");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int a=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO CONTINUE SHOPPING?");     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField n4;
    private javax.swing.JTextField n5;
    // End of variables declaration//GEN-END:variables

}
