/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * movies.java
 *
 * Created on 14 Apr, 2017, 4:15:22 PM
 */

package frames;

import frames.DISNEYSubForm;
import fandom.*;

/**
 *
 * @author MockingJay
 */
public class movies extends javax.swing.JFrame {

    /** Creates new form movies */
    public movies() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        N1 = new javax.swing.JLabel();
        N2 = new javax.swing.JLabel();
        N3 = new javax.swing.JLabel();
        N4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        N5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(790, 730));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        N1.setFont(new java.awt.Font("AR ESSENCE", 0, 36));
        N1.setForeground(new java.awt.Color(255, 255, 255));
        N1.setText("> MADAGASCAR");
        N1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N1MouseClicked(evt);
            }
        });
        getContentPane().add(N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        N2.setFont(new java.awt.Font("AR ESSENCE", 0, 36));
        N2.setForeground(new java.awt.Color(255, 255, 255));
        N2.setText(">   ICE AGE");
        N2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N2MouseClicked(evt);
            }
        });
        getContentPane().add(N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        N3.setFont(new java.awt.Font("AR ESSENCE", 0, 36));
        N3.setForeground(new java.awt.Color(255, 255, 255));
        N3.setText(">     D.C.");
        N3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N3MouseClicked(evt);
            }
        });
        getContentPane().add(N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        N4.setFont(new java.awt.Font("AR ESSENCE", 0, 36));
        N4.setForeground(new java.awt.Color(255, 255, 255));
        N4.setText("> THE AVENGERS");
        N4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N4MouseClicked(evt);
            }
        });
        getContentPane().add(N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Script", 1, 80));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 80));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(">");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        N5.setFont(new java.awt.Font("AR ESSENCE", 0, 36));
        N5.setForeground(new java.awt.Color(255, 255, 255));
        N5.setText("> TRANSFORMERS");
        N5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                N5MouseClicked(evt);
            }
        });
        getContentPane().add(N5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 270, -1));

        jLabel1.setFont(new java.awt.Font("AR ESSENCE", 0, 80));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fandom/movies bk.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
 String a=N1.getText();
       if(a.equals("> MADAGASCAR")==true)

{jLabel2.setEnabled(true);
 N1.setText(">   STAR WARS");
N2.setText("> DISNEY MOVIES");
N3.setText(">    ZOOTOPIA");
N4.setText(">    MINIONS");
N5.setText(">     X-MEN");}
       else jLabel2.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       String a=N1.getText();
       if(a.equals(">   STAR WARS")==true)
       {jLabel2.setEnabled(true);
       N1.setText("> MADAGASCAR");
       N2.setText(">  ICE AGE");
       N3.setText(">    D.C");
       N4.setText("> THE AVENGERS");
       N5.setText("> TRANFORMERS");
       }
       if(a.equals("> MADAGASCAR")){
       species n=new species();
       n.setVisible(true);
       dispose();}
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void N5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N5MouseClicked
       String a=N1.getText();
       if(a.equals("> MADAGASCAR"))
       {transformers n=new transformers();
       n.setVisible(true);
       dispose();}
       else if(a.equals(">   STAR WARS"))
       {xmen n=new xmen();
       n.setVisible(true);
       dispose();}
    }//GEN-LAST:event_N5MouseClicked

    private void N1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N1MouseClicked
      String a=N1.getText();
        if(a.equals("> MADAGASCAR"))
       {MADAGASCAR n=new MADAGASCAR();
        n.setVisible(true);}
        else
        {STARWARS b=new STARWARS();
      b.setVisible(true);}
      dispose();
      // TODO add your handling code here:
    }//GEN-LAST:event_N1MouseClicked

    private void N2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N2MouseClicked
 String a=N1.getText();
        if(a.equals("> MADAGASCAR"))
       {iceage n=new iceage();
        n.setVisible(true);}
        else
        {DISNEYSubForm b=new DISNEYSubForm();
      b.setVisible(true);}
      dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_N2MouseClicked

    private void N3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N3MouseClicked
    String a=N1.getText();
        if(a.equals("> MADAGASCAR"))
       {DC n=new DC();
        n.setVisible(true);}
        else
        {ZOOTOPIA b=new ZOOTOPIA();
      b.setVisible(true);}
      dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_N3MouseClicked

    private void N4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N4MouseClicked
  String a=N1.getText();
        if(a.equals("> MADAGASCAR"))
       {MARVEL n=new MARVEL();
        n.setVisible(true);}
        else
        {ZOOTOPIA b=new ZOOTOPIA();
      b.setVisible(true);}
      dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_N4MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel N1;
    private javax.swing.JLabel N2;
    private javax.swing.JLabel N3;
    private javax.swing.JLabel N4;
    private javax.swing.JLabel N5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

}
