/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 11 Aug, 2017, 3:19:08 PM
 */

package frames;

import java.awt.Component;
import java.awt.Window;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MockingJay
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        a = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fandom", "Item no.", "Item", "Size", "Qty", "Rate", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        a.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                aPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(a);
        a.getColumnModel().getColumn(0).setPreferredWidth(150);
        a.getColumnModel().getColumn(2).setPreferredWidth(500);
        a.getColumnModel().getColumn(4).setPreferredWidth(100);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 720, 270));

        jButton1.setText("CONTINUE TO PAYMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 240, -1));

        jButton2.setText("REMOVE SELECTED ITEM FROM CART");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 250, -1));

        jButton3.setText("CONTINUE SHOPPING");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       
     
            Window[] win=java.awt.Window.getWindows();
            for(int i=0;i<win.length;i++)
                win[i].dispose();
        payment n=new payment();
        n.setVisible(true);

                
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
 DefaultTableModel model=(DefaultTableModel)a.getModel();
int hey=a.getRowCount();
if (hey==0){
try{

Connection con=DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","diti");

Statement stmt=con.createStatement();
String query="select * from cart;";
ResultSet rs=stmt.executeQuery(query);

while(rs.next())
{
String fandom=rs.getString("fandom");
String itemno=rs.getString("item_no");
String item=rs.getString("item");
int qty=rs.getInt("quantity");
int rate=rs.getInt("rate");
int total=rs.getInt("total");
String size=rs.getString("size");

model.addRow(new Object[]{fandom,itemno,item,size,qty,rate,total});
        a.setRowHeight(35);
}}
catch(Exception e)
{;}}

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int heu=a.getSelectedRowCount();
        if (heu==0)
            JOptionPane.showMessageDialog(null, "Select altleast 1 item to be delected");

        else
        {            int[] hello=a.getSelectedRows();
                    
                     for(int i=0;i<heu;i++)
                     {String hey=(String) a.getValueAt(hello[i],1);
                      String hell=(String)a.getValueAt(hello[i],3);
       try{
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/ipproject","root","diti");
       Statement stmt=con.createStatement();
       String qwer="delete from cart where item_no=\""+hey+"\" and size=\""+hell+"\";";
       stmt.executeUpdate(qwer);
        NewJFrame n=new NewJFrame();
n.setVisible(true);

       JOptionPane.showMessageDialog(null,"Item successfully Deleted.");}
       catch(Exception e){JOptionPane.showMessageDialog(null, hey);}


               } 
       
       dispose();}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_aPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_aPropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable a;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
